// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACxRGauGx1iu-ShOF871fn5Dmm2dzbVGU',
    appId: '1:502094295209:web:9f16cb8583a2718178f9b8',
    messagingSenderId: '502094295209',
    projectId: 'smartlifepersonal',
    authDomain: 'smartlifepersonal.firebaseapp.com',
    storageBucket: 'smartlifepersonal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIW9ZcEjHCS5AtvOMihPxptTsJsrXlSM4',
    appId: '1:502094295209:android:f697eb25379a377478f9b8',
    messagingSenderId: '502094295209',
    projectId: 'smartlifepersonal',
    storageBucket: 'smartlifepersonal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRRXHohXLXac5FCqS4uln28H1O6-T_cQI',
    appId: '1:502094295209:ios:5ca4e7667224b10578f9b8',
    messagingSenderId: '502094295209',
    projectId: 'smartlifepersonal',
    storageBucket: 'smartlifepersonal.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRRXHohXLXac5FCqS4uln28H1O6-T_cQI',
    appId: '1:502094295209:ios:5ca4e7667224b10578f9b8',
    messagingSenderId: '502094295209',
    projectId: 'smartlifepersonal',
    storageBucket: 'smartlifepersonal.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACxRGauGx1iu-ShOF871fn5Dmm2dzbVGU',
    appId: '1:502094295209:web:afeccaa490cab58978f9b8',
    messagingSenderId: '502094295209',
    projectId: 'smartlifepersonal',
    authDomain: 'smartlifepersonal.firebaseapp.com',
    storageBucket: 'smartlifepersonal.firebasestorage.app',
  );
}
